[2024-04-17 15:51:37,226] INFO _log() L224  127.0.0.1 - - [17/Apr/2024 15:51:37] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\Users\F_Mota\AppData\Roaming\Python\Python310\site-packages\werkzeug\_internal.py L224 
[2024-04-17 15:56:45,800] INFO _log() L224  127.0.0.1 - - [17/Apr/2024 15:56:45] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\Users\F_Mota\AppData\Roaming\Python\Python310\site-packages\werkzeug\_internal.py L224 
[2024-04-17 16:00:56,812] INFO _log() L224  127.0.0.1 - - [17/Apr/2024 16:00:56] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\Users\F_Mota\AppData\Roaming\Python\Python310\site-packages\werkzeug\_internal.py L224 
[2024-04-17 16:01:21,206] INFO _log() L224  127.0.0.1 - - [17/Apr/2024 16:01:21] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\Users\F_Mota\AppData\Roaming\Python\Python310\site-packages\werkzeug\_internal.py L224 
[2024-04-17 16:01:25,832] INFO _log() L224  127.0.0.1 - - [17/Apr/2024 16:01:25] "OPTIONS /cliente?id=6 HTTP/1.1" 200 - - call_trace=C:\Users\F_Mota\AppData\Roaming\Python\Python310\site-packages\werkzeug\_internal.py L224 
[2024-04-17 16:01:25,852] INFO _log() L224  127.0.0.1 - - [17/Apr/2024 16:01:25] "DELETE /cliente?id=6 HTTP/1.1" 200 - - call_trace=C:\Users\F_Mota\AppData\Roaming\Python\Python310\site-packages\werkzeug\_internal.py L224 
[2024-04-17 16:01:28,392] INFO _log() L224  127.0.0.1 - - [17/Apr/2024 16:01:28] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\Users\F_Mota\AppData\Roaming\Python\Python310\site-packages\werkzeug\_internal.py L224 
[2024-04-17 16:01:34,106] INFO _log() L224  127.0.0.1 - - [17/Apr/2024 16:01:34] "OPTIONS /cliente?id=5 HTTP/1.1" 200 - - call_trace=C:\Users\F_Mota\AppData\Roaming\Python\Python310\site-packages\werkzeug\_internal.py L224 
[2024-04-17 16:01:34,126] INFO _log() L224  127.0.0.1 - - [17/Apr/2024 16:01:34] "DELETE /cliente?id=5 HTTP/1.1" 200 - - call_trace=C:\Users\F_Mota\AppData\Roaming\Python\Python310\site-packages\werkzeug\_internal.py L224 
[2024-04-17 16:18:05,819] INFO _log() L224  127.0.0.1 - - [17/Apr/2024 16:18:05] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\Users\F_Mota\AppData\Roaming\Python\Python310\site-packages\werkzeug\_internal.py L224 
[2024-04-17 16:18:37,087] INFO _log() L224  127.0.0.1 - - [17/Apr/2024 16:18:37] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\Users\F_Mota\AppData\Roaming\Python\Python310\site-packages\werkzeug\_internal.py L224 
[2024-04-17 16:19:15,500] INFO _log() L224  127.0.0.1 - - [17/Apr/2024 16:19:15] "POST /cliente HTTP/1.1" 200 - - call_trace=C:\Users\F_Mota\AppData\Roaming\Python\Python310\site-packages\werkzeug\_internal.py L224 
[2024-04-17 16:19:21,042] INFO _log() L224  127.0.0.1 - - [17/Apr/2024 16:19:21] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\Users\F_Mota\AppData\Roaming\Python\Python310\site-packages\werkzeug\_internal.py L224 
[2024-04-17 16:31:10,212] INFO _log() L224  127.0.0.1 - - [17/Apr/2024 16:31:10] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\Users\F_Mota\AppData\Roaming\Python\Python310\site-packages\werkzeug\_internal.py L224 
[2024-04-17 16:33:50,832] INFO _log() L224  127.0.0.1 - - [17/Apr/2024 16:33:50] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\Users\F_Mota\AppData\Roaming\Python\Python310\site-packages\werkzeug\_internal.py L224 
[2024-04-17 16:34:26,160] INFO _log() L224  127.0.0.1 - - [17/Apr/2024 16:34:26] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\Users\F_Mota\AppData\Roaming\Python\Python310\site-packages\werkzeug\_internal.py L224 
[2024-04-17 16:34:36,878] INFO _log() L224  127.0.0.1 - - [17/Apr/2024 16:34:36] "OPTIONS /cliente HTTP/1.1" 200 - - call_trace=C:\Users\F_Mota\AppData\Roaming\Python\Python310\site-packages\werkzeug\_internal.py L224 
[2024-04-17 16:34:36,884] INFO _log() L224  127.0.0.1 - - [17/Apr/2024 16:34:36] "[31m[1mPUT /cliente HTTP/1.1[0m" 422 - - call_trace=C:\Users\F_Mota\AppData\Roaming\Python\Python310\site-packages\werkzeug\_internal.py L224 
[2024-04-17 16:35:00,696] WARNING update_cliente() L101  Erro ao adicionar cliente 'Renato Lisboa da Silva', 'NoneType' object has no attribute 'nome' - call_trace=C:\Users\F_Mota\Downloads\aula_3_V2\aula-3\meu_app_api\app.py L101 
[2024-04-17 16:35:00,697] ERROR log_exception() L1449 Exception on /cliente [PUT] - call_trace=C:\Users\F_Mota\AppData\Roaming\Python\Python310\site-packages\flask\app.py L1449
Traceback (most recent call last):
  File "C:\Users\F_Mota\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\F_Mota\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1520, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\F_Mota\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1539, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\F_Mota\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1714, in make_response
    rv = jsonify(rv)
  File "C:\Users\F_Mota\AppData\Roaming\Python\Python310\site-packages\flask\json\__init__.py", line 302, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "C:\Users\F_Mota\AppData\Roaming\Python\Python310\site-packages\flask\json\__init__.py", line 132, in dumps
    return _json.dumps(obj, **kwargs)
  File "C:\Program Files\Python310\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\F_Mota\AppData\Roaming\Python\Python310\site-packages\flask\json\__init__.py", line 51, in default
    return super().default(o)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type AttributeError is not JSON serializable
[2024-04-17 16:35:00,753] INFO _log() L224  127.0.0.1 - - [17/Apr/2024 16:35:00] "[35m[1mPUT /cliente HTTP/1.1[0m" 500 - - call_trace=C:\Users\F_Mota\AppData\Roaming\Python\Python310\site-packages\werkzeug\_internal.py L224 
[2024-04-17 16:35:23,977] INFO _log() L224  127.0.0.1 - - [17/Apr/2024 16:35:23] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=C:\Users\F_Mota\AppData\Roaming\Python\Python310\site-packages\werkzeug\_internal.py L224 
[2024-04-17 16:35:24,184] INFO _log() L224  127.0.0.1 - - [17/Apr/2024 16:35:24] "[33mGET /openapi/static/css/swagger-ui.css.map HTTP/1.1[0m" 404 - - call_trace=C:\Users\F_Mota\AppData\Roaming\Python\Python310\site-packages\werkzeug\_internal.py L224 
[2024-04-17 16:35:24,192] INFO _log() L224  127.0.0.1 - - [17/Apr/2024 16:35:24] "[33mGET /openapi/static/js/swagger-ui-bundle.js.map HTTP/1.1[0m" 404 - - call_trace=C:\Users\F_Mota\AppData\Roaming\Python\Python310\site-packages\werkzeug\_internal.py L224 
[2024-04-17 16:35:24,195] INFO _log() L224  127.0.0.1 - - [17/Apr/2024 16:35:24] "[33mGET /openapi/static/js/swagger-ui-standalone-preset.js.map HTTP/1.1[0m" 404 - - call_trace=C:\Users\F_Mota\AppData\Roaming\Python\Python310\site-packages\werkzeug\_internal.py L224 
[2024-04-17 16:35:28,811] WARNING update_cliente() L101  Erro ao adicionar cliente 'Renato Lisboa da Silva', 'NoneType' object has no attribute 'nome' - call_trace=C:\Users\F_Mota\Downloads\aula_3_V2\aula-3\meu_app_api\app.py L101 
[2024-04-17 16:35:28,812] ERROR log_exception() L1449 Exception on /cliente [PUT] - call_trace=C:\Users\F_Mota\AppData\Roaming\Python\Python310\site-packages\flask\app.py L1449
Traceback (most recent call last):
  File "C:\Users\F_Mota\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\F_Mota\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1520, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\F_Mota\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1539, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\F_Mota\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1714, in make_response
    rv = jsonify(rv)
  File "C:\Users\F_Mota\AppData\Roaming\Python\Python310\site-packages\flask\json\__init__.py", line 302, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "C:\Users\F_Mota\AppData\Roaming\Python\Python310\site-packages\flask\json\__init__.py", line 132, in dumps
    return _json.dumps(obj, **kwargs)
  File "C:\Program Files\Python310\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\F_Mota\AppData\Roaming\Python\Python310\site-packages\flask\json\__init__.py", line 51, in default
    return super().default(o)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type AttributeError is not JSON serializable
[2024-04-17 16:35:28,815] INFO _log() L224  127.0.0.1 - - [17/Apr/2024 16:35:28] "[35m[1mPUT /cliente HTTP/1.1[0m" 500 - - call_trace=C:\Users\F_Mota\AppData\Roaming\Python\Python310\site-packages\werkzeug\_internal.py L224 
[2024-04-17 16:37:59,373] INFO _log() L224  127.0.0.1 - - [17/Apr/2024 16:37:59] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=C:\Users\F_Mota\AppData\Roaming\Python\Python310\site-packages\werkzeug\_internal.py L224 
