[2024-04-17 16:37:59,400] INFO _log() L224  127.0.0.1 - - [17/Apr/2024 16:37:59] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=C:\Users\F_Mota\AppData\Roaming\Python\Python310\site-packages\werkzeug\_internal.py L224 
[2024-04-17 16:37:59,438] INFO _log() L224  127.0.0.1 - - [17/Apr/2024 16:37:59] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\F_Mota\AppData\Roaming\Python\Python310\site-packages\werkzeug\_internal.py L224 
[2024-04-17 16:37:59,486] INFO _log() L224  127.0.0.1 - - [17/Apr/2024 16:37:59] "[33mGET /openapi/static/css/swagger-ui.css.map HTTP/1.1[0m" 404 - - call_trace=C:\Users\F_Mota\AppData\Roaming\Python\Python310\site-packages\werkzeug\_internal.py L224 
[2024-04-17 16:37:59,527] INFO _log() L224  127.0.0.1 - - [17/Apr/2024 16:37:59] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\F_Mota\AppData\Roaming\Python\Python310\site-packages\werkzeug\_internal.py L224 
[2024-04-17 16:37:59,582] INFO _log() L224  127.0.0.1 - - [17/Apr/2024 16:37:59] "[33mGET /openapi/static/js/swagger-ui-bundle.js.map HTTP/1.1[0m" 404 - - call_trace=C:\Users\F_Mota\AppData\Roaming\Python\Python310\site-packages\werkzeug\_internal.py L224 
[2024-04-17 16:37:59,630] INFO _log() L224  127.0.0.1 - - [17/Apr/2024 16:37:59] "[33mGET /openapi/static/js/swagger-ui-standalone-preset.js.map HTTP/1.1[0m" 404 - - call_trace=C:\Users\F_Mota\AppData\Roaming\Python\Python310\site-packages\werkzeug\_internal.py L224 
[2024-04-17 16:37:59,678] INFO _log() L224  127.0.0.1 - - [17/Apr/2024 16:37:59] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=C:\Users\F_Mota\AppData\Roaming\Python\Python310\site-packages\werkzeug\_internal.py L224 
[2024-04-17 16:37:59,706] INFO _log() L224  127.0.0.1 - - [17/Apr/2024 16:37:59] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\F_Mota\AppData\Roaming\Python\Python310\site-packages\werkzeug\_internal.py L224 
[2024-04-17 16:38:05,505] INFO _log() L224  [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 - call_trace=C:\Users\F_Mota\AppData\Roaming\Python\Python310\site-packages\werkzeug\_internal.py L224 
[2024-04-17 16:38:05,507] INFO _log() L224  [33mPress CTRL+C to quit[0m - call_trace=C:\Users\F_Mota\AppData\Roaming\Python\Python310\site-packages\werkzeug\_internal.py L224 
[2024-04-17 16:38:10,545] INFO _log() L224  127.0.0.1 - - [17/Apr/2024 16:38:10] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=C:\Users\F_Mota\AppData\Roaming\Python\Python310\site-packages\werkzeug\_internal.py L224 
[2024-04-17 16:38:10,747] INFO _log() L224  127.0.0.1 - - [17/Apr/2024 16:38:10] "GET /openapi/static/css/swagger-ui.css HTTP/1.1" 200 - - call_trace=C:\Users\F_Mota\AppData\Roaming\Python\Python310\site-packages\werkzeug\_internal.py L224 
[2024-04-17 16:38:10,755] INFO _log() L224  127.0.0.1 - - [17/Apr/2024 16:38:10] "GET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1" 200 - - call_trace=C:\Users\F_Mota\AppData\Roaming\Python\Python310\site-packages\werkzeug\_internal.py L224 
[2024-04-17 16:38:10,756] INFO _log() L224  127.0.0.1 - - [17/Apr/2024 16:38:10] "GET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1" 200 - - call_trace=C:\Users\F_Mota\AppData\Roaming\Python\Python310\site-packages\werkzeug\_internal.py L224 
[2024-04-17 16:38:10,769] INFO _log() L224  127.0.0.1 - - [17/Apr/2024 16:38:10] "[33mGET /openapi/static/css/swagger-ui.css.map HTTP/1.1[0m" 404 - - call_trace=C:\Users\F_Mota\AppData\Roaming\Python\Python310\site-packages\werkzeug\_internal.py L224 
[2024-04-17 16:38:10,860] INFO _log() L224  127.0.0.1 - - [17/Apr/2024 16:38:10] "[33mGET /openapi/static/js/swagger-ui-bundle.js.map HTTP/1.1[0m" 404 - - call_trace=C:\Users\F_Mota\AppData\Roaming\Python\Python310\site-packages\werkzeug\_internal.py L224 
[2024-04-17 16:38:10,905] INFO _log() L224  127.0.0.1 - - [17/Apr/2024 16:38:10] "[33mGET /openapi/static/js/swagger-ui-standalone-preset.js.map HTTP/1.1[0m" 404 - - call_trace=C:\Users\F_Mota\AppData\Roaming\Python\Python310\site-packages\werkzeug\_internal.py L224 
[2024-04-17 16:38:10,953] INFO _log() L224  127.0.0.1 - - [17/Apr/2024 16:38:10] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=C:\Users\F_Mota\AppData\Roaming\Python\Python310\site-packages\werkzeug\_internal.py L224 
[2024-04-17 16:38:10,961] INFO _log() L224  127.0.0.1 - - [17/Apr/2024 16:38:10] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\F_Mota\AppData\Roaming\Python\Python310\site-packages\werkzeug\_internal.py L224 
[2024-04-17 16:38:13,483] WARNING update_cliente() L101  Erro ao adicionar cliente 'Renato Lisboa da Silva', 'NoneType' object has no attribute 'nome' - call_trace=C:\Users\F_Mota\Downloads\aula_3_V2\aula-3\meu_app_api\app.py L101 
[2024-04-17 16:38:13,486] ERROR log_exception() L1449 Exception on /cliente [PUT] - call_trace=C:\Users\F_Mota\AppData\Roaming\Python\Python310\site-packages\flask\app.py L1449
Traceback (most recent call last):
  File "C:\Users\F_Mota\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\F_Mota\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1520, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\F_Mota\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1539, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\F_Mota\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1714, in make_response
    rv = jsonify(rv)
  File "C:\Users\F_Mota\AppData\Roaming\Python\Python310\site-packages\flask\json\__init__.py", line 302, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "C:\Users\F_Mota\AppData\Roaming\Python\Python310\site-packages\flask\json\__init__.py", line 132, in dumps
    return _json.dumps(obj, **kwargs)
  File "C:\Program Files\Python310\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\F_Mota\AppData\Roaming\Python\Python310\site-packages\flask\json\__init__.py", line 51, in default
    return super().default(o)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type AttributeError is not JSON serializable
[2024-04-17 16:38:13,491] INFO _log() L224  127.0.0.1 - - [17/Apr/2024 16:38:13] "[35m[1mPUT /cliente HTTP/1.1[0m" 500 - - call_trace=C:\Users\F_Mota\AppData\Roaming\Python\Python310\site-packages\werkzeug\_internal.py L224 
[2024-04-17 16:39:20,162] INFO _log() L224  127.0.0.1 - - [17/Apr/2024 16:39:20] "POST /cliente HTTP/1.1" 200 - - call_trace=C:\Users\F_Mota\AppData\Roaming\Python\Python310\site-packages\werkzeug\_internal.py L224 
[2024-04-17 16:39:35,450] WARNING update_cliente() L101  Erro ao adicionar cliente '523452477744', 'NoneType' object has no attribute 'nome' - call_trace=C:\Users\F_Mota\Downloads\aula_3_V2\aula-3\meu_app_api\app.py L101 
[2024-04-17 16:39:35,453] ERROR log_exception() L1449 Exception on /cliente [PUT] - call_trace=C:\Users\F_Mota\AppData\Roaming\Python\Python310\site-packages\flask\app.py L1449
Traceback (most recent call last):
  File "C:\Users\F_Mota\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\F_Mota\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1520, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\F_Mota\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1539, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\F_Mota\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1714, in make_response
    rv = jsonify(rv)
  File "C:\Users\F_Mota\AppData\Roaming\Python\Python310\site-packages\flask\json\__init__.py", line 302, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "C:\Users\F_Mota\AppData\Roaming\Python\Python310\site-packages\flask\json\__init__.py", line 132, in dumps
    return _json.dumps(obj, **kwargs)
  File "C:\Program Files\Python310\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\F_Mota\AppData\Roaming\Python\Python310\site-packages\flask\json\__init__.py", line 51, in default
    return super().default(o)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type AttributeError is not JSON serializable
[2024-04-17 16:39:35,457] INFO _log() L224  127.0.0.1 - - [17/Apr/2024 16:39:35] "[35m[1mPUT /cliente HTTP/1.1[0m" 500 - - call_trace=C:\Users\F_Mota\AppData\Roaming\Python\Python310\site-packages\werkzeug\_internal.py L224 
[2024-04-17 16:39:57,593] INFO _log() L224  127.0.0.1 - - [17/Apr/2024 16:39:57] "POST /cliente HTTP/1.1" 200 - - call_trace=C:\Users\F_Mota\AppData\Roaming\Python\Python310\site-packages\werkzeug\_internal.py L224 
